type: java
dependencies:
 - examples/java-foo
 - org.slf4j:slf4j-simple:1.7.7
test-dependencies:
 - junit:junit:4.8.1
 - org.testpackage:testpackage:0.3.0
main-class: mycode.Hello
archive:
  type: jar
  groupId: org.example
  artifactId: hello